### ISSUE TITLE
Headings margin too small

### ISSUE THREAD

**Issue by yamiko-ninja** [SayenkoDesign/Noel-Interior-Design#33]
The margin between headings like h1 and the content in the left col is too small

**Comment by yamiko-ninja** [comment]
on the other hand they are too big on some pages as well.

Make sure they are all the same. I would grab the spacing from this page and use it on all h1-h6. 
https://projects.invisionapp.com/d/main#/console/7056901/155682260/preview

**Comment by tolentino3575** [comment]
issue #33 done, pr made
