### ISSUE TITLE
Image collections should oprn up fancybox gallery when clicked

### ISSUE THREAD

**Issue by yamiko-ninja** [SayenkoDesign/Noel-Interior-Design#38]

**Comment by tolentino3575** [comment]
issue #38 done, pr made

for fancybox v2.1.5, to change overlay color it requires rgba (web/scripts/app.js line 30). no matter what, rgba(255, 255, 255, x) sets as a gray for me when it should be white.

**Comment by tolentino3575** [comment]
issue #38 done, pr made, opacity fixed
