### ISSUE TITLE
Create color Pallate

### ISSUE THREAD

**Issue by yamiko-ninja** [SayenkoDesign/Noel-Interior-Design#4]
Create color variables for colors in style guide in invision. If there are colors in the photoshop files but not the guide add them as well.

The photoshop files can be downloaded in invision under assets for the project.

**Comment by yamiko-ninja** [comment]
Note you may want to add some of the colors to foundation palate. See http://foundation.zurb.com/sites for more information about the color palate /docs/global.html

**Comment by tolentino3575** [comment]
Issue #4 done
