### ISSUE TITLE
Text settings

### ISSUE THREAD

**Issue by yamiko-ninja** [SayenkoDesign/Noel-Interior-Design#5]
Set values for the following settings in settings.scss

$body-font-color, $body-font-family, $body-font-color, $header-font-family, $header-font-weight, $header-font-style, $header-sizes, $header-color, $header-lineheight, $header-margin-bottom, $paragraph-lineheight, $paragraph-margin-bottom, $anchor-color, $anchor-color-hover, $anchor-text-decoration, $anchor-text-decoration-hover

**Comment by yamiko-ninja** [comment]
see http://foundation.zurb.com/sites/docs/typography-base.html for more info on the settings

**Comment by tolentino3575** [comment]
Issue #5 done
